plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.shark'
version = '1.0.0'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
  // JWT 관련 디펜던시
  // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api
  // JWT 생성, 서명, 인코딩, 파싱 등 기능의 인터페이스를 제공
  implementation("io.jsonwebtoken:jjwt-api:0.12.3")
  // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl
  // JJWT API의 실제 구현체를 포함
  runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.3")
  // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson
  // Jackson 라이브러리의 JSON 처리 기능을 활용하여 토큰의 데이터와 JSON 데이터의 직렬화/역직렬화 제공
  runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.12.3")
  
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  compileOnly 'org.projectlombok:lombok'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  runtimeOnly 'com.mysql:mysql-connector-j:8.0.33'
  annotationProcessor 'org.projectlombok:lombok'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.security:spring-security-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
